services:
  app:
    build: .
    depends_on:
    - postgres
    volumes:
    - ./:/go/src/app
    - .env:/go/src/app/.env
    ports:
      - "8080:8080"
    tty: true

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - feature_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  feature_data: